version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    ignore:
      update-types: ["version-update:semver-patch", "version-update:semver-minor"]
